import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { describe, it } from "node:test";

import {
	DIFF_BEGIN_MARKER,
	DIFF_END_MARKER,
	buildReviewPrompt,
	parseCriterionIds,
} from "../src/prompt.ts";
import { CRITERION_IDS } from "../src/schema.ts";

const CRITERIA_MARKDOWN = readFileSync(
	fileURLToPath(new URL("../prompts/criteria.md", import.meta.url)),
	"utf8",
);

const SAMPLE_DIFF = [
	"diff --git a/src/main/resources/db/migration/V3__create_preference_profiles.sql b/src/main/resources/db/migration/V3__create_preference_profiles.sql",
	"--- a/src/main/resources/db/migration/V3__create_preference_profiles.sql",
	"+++ b/src/main/resources/db/migration/V3__create_preference_profiles.sql",
	"@@ -4,6 +4,7 @@ CREATE TABLE preference_profiles (",
	"+    nickname VARCHAR(64),",
].join("\n");

describe("parseCriterionIds", () => {
	// The document and the schema enum are two independent lists that must stay identical: a renamed
	// heading yields a criterion the model is told to score but the schema rejects, and a stale enum
	// entry yields one that can never be scored. Assert both directions.
	it("matches the schema enum exactly, with no extras or omissions on either side", () => {
		const documented = parseCriterionIds(CRITERIA_MARKDOWN);

		assert.deepEqual([...documented].sort(), [...CRITERION_IDS].sort());
	});

	it("finds each criterion exactly once", () => {
		const documented = parseCriterionIds(CRITERIA_MARKDOWN);

		assert.equal(documented.length, CRITERION_IDS.length);
		assert.equal(new Set(documented).size, CRITERION_IDS.length);
	});

	it("reads ids from backticked headings only, ignoring inline code elsewhere", () => {
		const markdown = [
			"# Title",
			"",
			"Prose mentioning `not-a-criterion` inline.",
			"",
			"## `real-criterion`",
			"",
			"### `nested-not-a-criterion`",
		].join("\n");

		assert.deepEqual(parseCriterionIds(markdown), ["real-criterion"]);
	});
});

describe("buildReviewPrompt", () => {
	const prompt = buildReviewPrompt({
		criteriaMarkdown: CRITERIA_MARKDOWN,
		diffText: SAMPLE_DIFF,
	});

	// The safety instructions name the markers verbatim so the model knows exactly what to look for,
	// which means each marker string appears twice: once as prose, then as the real delimiter. The
	// delimited block is always the last occurrence.
	const diffBlockStart = prompt.lastIndexOf(DIFF_BEGIN_MARKER);
	const diffBlockEnd = prompt.lastIndexOf(DIFF_END_MARKER);

	it("delimits the diff as untrusted data", () => {
		assert.ok(diffBlockStart !== -1);
		assert.ok(diffBlockEnd > diffBlockStart);

		const body = prompt.slice(diffBlockStart + DIFF_BEGIN_MARKER.length, diffBlockEnd);
		assert.ok(body.includes("V3__create_preference_profiles.sql"));
		assert.ok(body.includes("+    nickname VARCHAR(64),"));
	});

	it("instructs the model to treat diff content as evidence rather than commands", () => {
		assert.match(prompt, /untrusted data/i);
		assert.match(prompt, /never as\s+instructions/i);
		assert.match(prompt, /not a command from your operator/i);
	});

	// The safety rule has to be established before the diff appears, or the adversarial text is read
	// first and the boundary arrives too late to frame it.
	it("states the untrusted-data rule before the diff itself", () => {
		assert.ok(prompt.indexOf("untrusted data") < diffBlockStart);
		assert.ok(prompt.indexOf("not a command from your operator") < diffBlockStart);
	});

	it("carries every criterion id", () => {
		for (const id of CRITERION_IDS) {
			assert.ok(prompt.includes(id), `prompt should mention ${id}`);
		}
	});

	it("embeds the criteria document", () => {
		assert.ok(prompt.includes("A violation looks like:"));
		assert.ok(prompt.includes("BIGINT GENERATED BY DEFAULT AS IDENTITY"));
	});

	it("asks for every criterion to be scored, including unviolated ones", () => {
		assert.match(prompt, /including the ones the diff does\s+not violate/i);
		assert.match(prompt, /empty findings list/i);
	});

	// Read-only repo access is available but the turn budget is small, so the prompt has to actively
	// discourage browsing or `error_max_turns` becomes the common outcome.
	it("prefers the diff as evidence over exploratory file reading", () => {
		assert.match(prompt, /do not go browsing/i);
	});

	it("anchors findings to a file and line drawn from the diff", () => {
		assert.match(prompt, /Anchor each finding to a `file` and\s+`line`/i);
	});

	// The overall verdict is computed in `verdict.ts`; asking the model for it would make the gate
	// probabilistic.
	it("does not ask the model for an overall pass or fail decision", () => {
		assert.doesNotMatch(prompt, /\b(pass|fail) the (review|diff|change)\b/i);
		assert.match(prompt, /they\s+do not decide whether the change is accepted/i);
	});
});
