CREATE TABLE preference_profiles (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            BIGINT      NOT NULL,
    experience_level   VARCHAR(32) NOT NULL,
    difficulty_band    VARCHAR(32) NOT NULL,
    novelty_preference VARCHAR(32) NOT NULL,
    created_at         TIMESTAMP   NOT NULL,
    updated_at         TIMESTAMP   NOT NULL,
    CONSTRAINT uq_preference_profiles_user_id UNIQUE (user_id),
    CONSTRAINT fk_preference_profiles_user_id FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE preference_profile_regions (
    profile_id BIGINT       NOT NULL,
    country    VARCHAR(255) NOT NULL,
    CONSTRAINT fk_preference_profile_regions_profile FOREIGN KEY (profile_id) REFERENCES preference_profiles (id),
    CONSTRAINT uq_preference_profile_regions UNIQUE (profile_id, country)
);
