CREATE TABLE visited_resorts (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT    NOT NULL,
    resort_id  BIGINT    NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uq_visited_user_resort UNIQUE (user_id, resort_id)
);
